ignore:
    - "**/*.pb.go"
    - "**/testInitializerInputs.go"
    - "**/testInitializerVMOutput.go"
    - "hosttest/**/*"
    - "mock/**/*"
    - "scenario/*"
    - "scenario/**/*"
    - "test/**/*"
    - "testcommon/*"
    - "testcommon/**/*"
